-- ════════════════════════════════════════════════════════════════════
-- ForgeMinds source_catalog — civic / local_govt
-- Curated by source-catalog-curator subagent on 2026-05-15
-- All URLs verified reachable + producing valid RSS 2.0 feed content
-- Scope: US local + state government, civic-tech, FOIA-focused journalism,
--        govtech, election admin, federal/state policy desks
-- ════════════════════════════════════════════════════════════════════

insert into public.source_catalog (
  name, type, url, description, categories, subcategories,
  paywall_tier, paywall_cost_usd_monthly, update_cadence, geography,
  quality_score, requires_oauth, oauth_provider, recommended_for_topics
) values
  (
    'StateScoop',
    'rss',
    'https://statescoop.com/feed/',
    'Daily trade publication covering state government IT, cybersecurity, data, and digital services — the go-to for state CIO news.',
    array['civic', 'tech'],
    array['local_govt', 'govtech'],
    'free',
    null,
    'daily',
    array['us'],
    0.75,
    false,
    null,
    array['state_government', 'govtech', 'state_cio', 'public_sector_cybersecurity', 'digital_services']
  ),
  (
    'ProPublica',
    'rss',
    'https://www.propublica.org/feeds/propublica/main',
    'Nonprofit investigative newsroom; deep accountability journalism on federal + state government, including state-desk investigations.',
    array['civic', 'geopolitics'],
    array['local_govt', 'foia_journalism'],
    'free',
    null,
    'daily',
    array['us'],
    0.92,
    false,
    null,
    array['investigative_journalism', 'government_accountability', 'state_policy', 'foia', 'public_records']
  ),
  (
    'GAO WatchBlog',
    'rss',
    'https://www.gao.gov/blog/feed',
    'Government Accountability Office blog distilling GAO reports — federal waste, oversight findings, intergovernmental program audits relevant to state + local recipients.',
    array['civic'],
    array['local_govt', 'federal_oversight'],
    'free',
    null,
    'weekly',
    array['us'],
    0.95,
    false,
    null,
    array['government_accountability', 'federal_oversight', 'gao_reports', 'public_spending', 'audit']
  ),
  (
    'StateTech Magazine',
    'rss',
    'https://feeds.feedburner.com/StateTech',
    'Coverage of cybersecurity, cloud, networking, and digital workspace tooling for state and local government IT leaders.',
    array['civic', 'tech'],
    array['local_govt', 'govtech'],
    'free',
    null,
    'weekly',
    array['us'],
    0.7,
    false,
    null,
    array['state_government_it', 'public_sector_cybersecurity', 'govtech', 'nascio', 'state_cio']
  ),
  (
    'Federal News Network — Newscast',
    'rss',
    'https://federalnewsnetwork.com/category/federal-newscast/feed/',
    'Daily federal newscast covering workforce, defense, agency operations — context for state + local recipients of federal programs.',
    array['civic'],
    array['local_govt', 'federal_oversight'],
    'free',
    null,
    'daily',
    array['us'],
    0.72,
    false,
    null,
    array['federal_workforce', 'federal_agencies', 'gov_operations', 'federal_state_programs']
  ),
  (
    'Federal News Network — All News',
    'rss',
    'https://federalnewsnetwork.com/feed/',
    'Full-stream federal government news — workforce, contracting, agency policy, congressional action — useful for state recipients of federal funds.',
    array['civic'],
    array['local_govt', 'federal_oversight'],
    'free',
    null,
    'daily',
    array['us'],
    0.7,
    false,
    null,
    array['federal_government', 'agency_news', 'gov_contracting', 'congressional_action']
  ),
  (
    'Nextgov / FCW',
    'rss',
    'https://www.nextgov.com/rss/all/',
    'Federal government technology, cybersecurity, and AI policy news — overlaps state/local through shared CISA + NIST guidance.',
    array['civic', 'tech'],
    array['local_govt', 'govtech'],
    'free',
    null,
    'daily',
    array['us'],
    0.75,
    false,
    null,
    array['federal_it', 'public_sector_ai', 'cisa', 'government_cybersecurity', 'federal_acquisition']
  ),
  (
    'Government Executive',
    'rss',
    'https://www.govexec.com/rss/all/',
    'Federal management + workforce trade pub; covers intergovernmental program shifts that flow to state and local recipients.',
    array['civic'],
    array['local_govt', 'federal_oversight'],
    'free',
    null,
    'daily',
    array['us'],
    0.72,
    false,
    null,
    array['federal_management', 'gov_workforce', 'federal_policy', 'intergov_programs']
  ),
  (
    'Stateline',
    'rss',
    'https://stateline.org/feed/',
    'Nonprofit newsroom (Pew-founded) focused exclusively on state policy — redistricting, housing, criminal justice, public health, statehouse politics.',
    array['civic'],
    array['local_govt', 'state_policy'],
    'free',
    null,
    'daily',
    array['us'],
    0.88,
    false,
    null,
    array['state_policy', 'state_legislatures', 'redistricting', 'state_budget', 'criminal_justice', 'statehouse_politics']
  ),
  (
    'electionline Weekly',
    'rss',
    'https://electionline.org/feed',
    'Election administration newsletter from the Election Center — the source-of-record for state + local election officials, audits, certification, voting tech.',
    array['civic'],
    array['local_govt', 'election_admin'],
    'free',
    null,
    'weekly',
    array['us'],
    0.85,
    false,
    null,
    array['election_administration', 'voting_technology', 'election_officials', 'ballot_security', 'voter_registration']
  ),
  (
    'US Census Bureau — Press Releases',
    'rss',
    'https://www.census.gov/content/census/en/newsroom/press-releases.xml',
    'Official Census Bureau press releases covering demographic, economic, and public-finance data — including state + local public pension and government survey releases.',
    array['civic'],
    array['local_govt', 'public_data'],
    'free',
    null,
    'weekly',
    array['us'],
    0.95,
    false,
    null,
    array['census_data', 'public_pensions', 'demographic_data', 'government_finance', 'state_local_survey']
  ),
  (
    'US Census Bureau — Economic Indicators',
    'rss',
    'https://www.census.gov/economic-indicators/indicator.xml',
    'Official Census Bureau economic indicators feed — manufacturing, trade, housing, retail data points that drive state/local fiscal planning.',
    array['civic', 'finance'],
    array['local_govt', 'public_data'],
    'free',
    null,
    'weekly',
    array['us'],
    0.95,
    false,
    null,
    array['economic_indicators', 'census_economic_data', 'state_fiscal_planning', 'public_finance']
  )
on conflict (type, url) do update set
  name = excluded.name,
  description = excluded.description,
  categories = excluded.categories,
  subcategories = excluded.subcategories,
  paywall_tier = excluded.paywall_tier,
  paywall_cost_usd_monthly = excluded.paywall_cost_usd_monthly,
  update_cadence = excluded.update_cadence,
  geography = excluded.geography,
  quality_score = excluded.quality_score,
  requires_oauth = excluded.requires_oauth,
  oauth_provider = excluded.oauth_provider,
  recommended_for_topics = excluded.recommended_for_topics,
  updated_at = now();
