-- ════════════════════════════════════════════════════════════════════
-- ForgeMinds source_catalog — career / job_search
-- Curated by source-catalog-curator subagent on 2026-05-15
-- All URLs verified reachable + producing valid feed content
-- ════════════════════════════════════════════════════════════════════

insert into public.source_catalog (
  name, type, url, description, categories, subcategories,
  paywall_tier, paywall_cost_usd_monthly, update_cadence, geography,
  quality_score, requires_oauth, oauth_provider, recommended_for_topics
) values
  (
    'The Pragmatic Engineer Blog',
    'rss',
    'https://blog.pragmaticengineer.com/rss/',
    'Gergely Orosz''s blog covering Big Tech engineering practices, hiring market, layoffs, compensation trends, and career advice for software engineers.',
    array['career', 'tech'],
    array['job_search', 'tech_careers'],
    'freemium',
    15.00,
    'weekly',
    array['global'],
    0.85,
    false,
    null,
    array['tech_careers', 'engineering_hiring', 'layoffs', 'compensation_trends', 'big_tech', 'career_pivots', 'interview_prep']
  ),
  (
    'The Pragmatic Engineer Newsletter',
    'rss',
    'https://newsletter.pragmaticengineer.com/feed',
    'Newsletter edition of The Pragmatic Engineer — weekly deep-dives on software industry trends, hiring market signals, and engineering career navigation.',
    array['career', 'tech'],
    array['job_search', 'tech_careers'],
    'freemium',
    15.00,
    'weekly',
    array['global'],
    0.85,
    false,
    null,
    array['tech_careers', 'engineering_hiring', 'forward_deployed_engineering', 'compensation_trends', 'career_pivots']
  ),
  (
    'Lenny''s Newsletter',
    'rss',
    'https://www.lennysnewsletter.com/feed',
    'Lenny Rachitsky''s newsletter on product management careers, growth roles, hiring advice, and interviews with PM/product leaders at top tech companies.',
    array['career', 'tech'],
    array['job_search', 'product_management_careers'],
    'freemium',
    18.00,
    'weekly',
    array['global'],
    0.80,
    false,
    null,
    array['product_management_careers', 'tech_careers', 'pm_interviews', 'career_pivots', 'growth_roles', 'startup_hiring']
  ),
  (
    'Ask a Manager',
    'rss',
    'https://www.askamanager.org/feed',
    'Alison Green''s long-running workplace advice column covering job searches, interviews, resumes, salary negotiation, and on-the-job navigation — high-trust non-tech career guidance.',
    array['career'],
    array['job_search', 'workplace_advice'],
    'free',
    null,
    'daily',
    array['us', 'global'],
    0.80,
    false,
    null,
    array['interview_prep', 'resume_guidance', 'salary_negotiation', 'workplace_navigation', 'manager_relations', 'career_transitions', 'non_tech_careers']
  ),
  (
    'HR Dive',
    'rss',
    'https://www.hrdive.com/feeds/news/',
    'Trade publication covering HR industry news, hiring trends, talent acquisition strategy, and workforce policy — useful for understanding employer-side hiring dynamics.',
    array['career'],
    array['job_search', 'hr_industry'],
    'free',
    null,
    'daily',
    array['us'],
    0.70,
    false,
    null,
    array['hiring_trends', 'talent_acquisition', 'recruiting_industry', 'hr_policy', 'workforce_trends', 'employer_perspective']
  ),
  (
    'Fast Company Work Life',
    'rss',
    'https://www.fastcompany.com/work-life/rss',
    'Fast Company''s work + careers vertical covering workplace trends, career strategy, AI''s impact on jobs, remote work, and leadership for ambitious professionals.',
    array['career'],
    array['job_search', 'workplace_trends'],
    'freemium',
    null,
    'daily',
    array['us', 'global'],
    0.70,
    false,
    null,
    array['workplace_trends', 'career_strategy', 'ai_and_jobs', 'remote_work', 'leadership', 'career_pivots']
  ),
  (
    'Bloomberg Work Shift',
    'rss',
    'https://feeds.bloomberg.com/work-shift/news.rss',
    'Bloomberg''s labor and workplace vertical covering hiring/firing at major companies, labor market signals, banking and finance recruiting, and AI workforce impact.',
    array['career', 'finance'],
    array['job_search', 'labor_market'],
    'paid',
    34.99,
    'daily',
    array['us', 'global'],
    0.85,
    false,
    null,
    array['labor_market', 'finance_careers', 'big_tech_hiring', 'layoffs', 'ai_and_jobs', 'compensation_trends', 'executive_hiring']
  ),
  (
    'Hacker News — Hiring & Layoffs',
    'rss',
    'https://hnrss.org/newest?q=hiring+OR+layoffs+OR+jobs',
    'Filtered Hacker News feed for stories about hiring, layoffs, and the tech job market — surfaces real-time community discussion of major tech workforce events.',
    array['career', 'tech'],
    array['job_search', 'tech_careers'],
    'free',
    null,
    'hourly',
    array['global'],
    0.55,
    false,
    null,
    array['tech_careers', 'layoffs', 'big_tech_hiring', 'job_market_signals', 'community_discussion']
  ),
  (
    'Hacker News — Layoff Tracker',
    'rss',
    'https://hnrss.org/newest?q=layoff',
    'Filtered Hacker News feed dedicated to layoff stories — near real-time signal of tech workforce reductions and the discussion around them.',
    array['career', 'tech'],
    array['job_search', 'layoffs'],
    'free',
    null,
    'hourly',
    array['global'],
    0.55,
    false,
    null,
    array['layoffs', 'tech_workforce_reductions', 'big_tech', 'job_market_signals', 'ai_displacement']
  ),
  (
    'Hacker News Who Is Hiring (YC Jobs)',
    'rss',
    'https://hnrss.org/jobs',
    'Live YC company job postings feed — direct-from-startup hiring signals across engineering, product, growth, and technical roles at YC-backed companies.',
    array['career', 'tech'],
    array['job_search', 'startup_jobs'],
    'free',
    null,
    'daily',
    array['us', 'global'],
    0.60,
    false,
    null,
    array['startup_jobs', 'yc_companies', 'engineering_hiring', 'product_roles', 'growth_roles', 'remote_work']
  ),
  (
    'Remote OK Jobs',
    'rss',
    'https://remoteok.com/remote-jobs.rss',
    'Remote-only job listings aggregated globally across engineering, design, marketing, and operations — primary feed for users tracking the remote job market.',
    array['career', 'tech'],
    array['job_search', 'remote_jobs'],
    'free',
    null,
    'daily',
    array['global'],
    0.55,
    false,
    null,
    array['remote_jobs', 'tech_careers', 'engineering_hiring', 'remote_work', 'global_hiring']
  )
on conflict (type, url) do update set
  name = excluded.name,
  description = excluded.description,
  categories = excluded.categories,
  subcategories = excluded.subcategories,
  paywall_tier = excluded.paywall_tier,
  paywall_cost_usd_monthly = excluded.paywall_cost_usd_monthly,
  update_cadence = excluded.update_cadence,
  geography = excluded.geography,
  quality_score = excluded.quality_score,
  requires_oauth = excluded.requires_oauth,
  oauth_provider = excluded.oauth_provider,
  recommended_for_topics = excluded.recommended_for_topics,
  updated_at = now();
