-- ════════════════════════════════════════════════════════════════════
-- ForgeMinds source_catalog — health / preventive
-- Curated by source-catalog-curator subagent on 2026-05-15
-- All URLs verified reachable via WebFetch + producing valid feed content
-- Scope: preventive health, public health, wellness, nutrition science,
--        exercise physiology, screening guidelines, vaccinations.
-- Distinct from `medicine` (treatment) and `lifestyle/longevity` (popular).
-- ════════════════════════════════════════════════════════════════════

insert into public.source_catalog (
  name, type, url, description, categories, subcategories,
  paywall_tier, paywall_cost_usd_monthly, update_cadence, geography,
  quality_score, requires_oauth, oauth_provider, recommended_for_topics
) values
  (
    'CDC MMWR (Morbidity and Mortality Weekly Report)',
    'rss',
    'https://tools.cdc.gov/api/v2/resources/media/342778.rss',
    'CDC''s primary publication for timely, authoritative public-health surveillance data, outbreak reports, and prevention guidelines. Gold-standard source for US disease trends.',
    array['health', 'sciences'],
    array['preventive', 'epidemiology'],
    'free',
    null,
    'weekly',
    array['us', 'global'],
    0.98,
    false,
    null,
    array['epidemiology', 'outbreak_surveillance', 'vaccinations', 'public_health', 'infectious_disease', 'screening_guidelines', 'environmental_health']
  ),
  (
    'CDC Online Newsroom',
    'rss',
    'https://tools.cdc.gov/podcasts/feed.asp?feedid=183',
    'CDC press releases and official statements on outbreaks, immunization updates, public health initiatives, and policy announcements.',
    array['health'],
    array['preventive'],
    'free',
    null,
    'daily',
    array['us', 'global'],
    0.95,
    false,
    null,
    array['outbreak_surveillance', 'vaccinations', 'public_health', 'health_policy', 'infectious_disease']
  ),
  (
    'WHO News',
    'rss',
    'https://www.who.int/rss-feeds/news-english.xml',
    'World Health Organization official news: global disease elimination milestones, outbreak warnings, public-health policy guidance, and cross-border health threats.',
    array['health', 'geopolitics'],
    array['preventive'],
    'free',
    null,
    'daily',
    array['global', 'eu', 'us'],
    0.97,
    false,
    null,
    array['global_health', 'epidemiology', 'outbreak_surveillance', 'vaccinations', 'public_health', 'infectious_disease', 'tobacco_control']
  ),
  (
    'STAT News',
    'rss',
    'https://www.statnews.com/feed/',
    'Reuters-quality biotech and public-health journalism with strong editorial standards. Covers FDA decisions, drug pricing, outbreak response, and health policy with reporter bylines.',
    array['health'],
    array['preventive', 'medicine'],
    'freemium',
    null,
    'hourly',
    array['us', 'global'],
    0.85,
    false,
    null,
    array['public_health', 'health_policy', 'fda_decisions', 'outbreak_response', 'biotech', 'drug_pricing']
  ),
  (
    'KFF Health News',
    'rss',
    'https://kffhealthnews.org/feed/',
    'Independent newsroom (formerly Kaiser Health News) covering US health policy, public-health funding, healthcare access, and government health programs. Strong investigative track record.',
    array['health'],
    array['preventive'],
    'free',
    null,
    'daily',
    array['us'],
    0.88,
    false,
    null,
    array['health_policy', 'public_health', 'healthcare_access', 'health_funding', 'medicaid', 'medicare']
  ),
  (
    'Ground Truths (Eric Topol)',
    'rss',
    'https://erictopol.substack.com/feed',
    'Eric Topol''s Substack on evidence-based medicine, AI in healthcare, infectious disease, and screening science. Cardiologist + Scripps director; cites primary research throughout.',
    array['health', 'sciences'],
    array['preventive'],
    'freemium',
    null,
    'weekly',
    array['us', 'global'],
    0.90,
    false,
    null,
    array['evidence_based_medicine', 'screening_science', 'infectious_disease', 'ai_in_health', 'cardiology', 'longevity']
  ),
  (
    'NutritionFacts.org',
    'rss',
    'https://nutritionfacts.org/feed/',
    'Dr. Michael Greger''s nutrition-science platform synthesizing peer-reviewed research on diet, microbiome, chronic disease prevention. Strong plant-based lens — read critically.',
    array['health'],
    array['preventive'],
    'free',
    null,
    'weekly',
    array['us', 'global'],
    0.70,
    false,
    null,
    array['nutrition_science', 'plant_based_diet', 'microbiome', 'chronic_disease_prevention', 'cancer_prevention', 'cardiovascular_diet']
  ),
  (
    'Peter Attia MD',
    'rss',
    'https://peterattiamd.com/feed/',
    'Peter Attia''s long-form newsletter + podcast on longevity, preventive medicine, cancer screening, metabolic health, and exercise physiology. Cites primary literature with depth.',
    array['health'],
    array['preventive'],
    'freemium',
    null,
    'weekly',
    array['us', 'global'],
    0.85,
    false,
    null,
    array['longevity', 'cancer_screening', 'metabolic_health', 'exercise_physiology', 'cardiovascular_prevention', 'preventive_medicine']
  ),
  (
    'NPR Health Shots',
    'rss',
    'https://feeds.npr.org/1128/rss.xml',
    'NPR''s health desk covering public health, mental health, FDA policy, healthcare access, and behavioral health research with editorial fact-checking standards.',
    array['health'],
    array['preventive'],
    'free',
    null,
    'daily',
    array['us'],
    0.82,
    false,
    null,
    array['public_health', 'mental_health', 'health_policy', 'healthcare_access', 'behavioral_health', 'fda_decisions']
  ),
  (
    'CDC COVID-19 Updates',
    'rss',
    'https://tools.cdc.gov/api/v2/resources/media/403372.rss',
    'CDC channel for COVID-19 specific updates. Currently low item volume — keep for surge periods; pair with MMWR for general infectious-disease coverage.',
    array['health'],
    array['preventive'],
    'free',
    null,
    'weekly',
    array['us', 'global'],
    0.75,
    false,
    null,
    array['covid_19', 'respiratory_virus', 'pandemic_preparedness']
  )
on conflict (type, url) do update set
  name = excluded.name,
  description = excluded.description,
  categories = excluded.categories,
  subcategories = excluded.subcategories,
  paywall_tier = excluded.paywall_tier,
  paywall_cost_usd_monthly = excluded.paywall_cost_usd_monthly,
  update_cadence = excluded.update_cadence,
  geography = excluded.geography,
  quality_score = excluded.quality_score,
  recommended_for_topics = excluded.recommended_for_topics,
  updated_at = now();
