-- ════════════════════════════════════════════════════════════════════
-- ForgeMinds — Phase 1.5: source_catalog (AI-Assisted Source Discovery)
-- ════════════════════════════════════════════════════════════════════
-- Phase 1.5 replaces the "paste 10 RSS URLs" onboarding with a
-- conversational AI agent that walks each user through picking sources
-- based on their interests, depth, cadence, and paywall comfort.
--
-- For that agent to work, it needs a curated catalog of high-quality
-- sources to RAG over and recommend from. This migration creates the
-- public read-only catalog table.
--
-- Core principles (per plan §1.5):
--   - Public read (every user sees same catalog), service_role write
--     (only the seed/curator subagent updates).
--   - Hand-curated initial seed via `source-catalog-curator` subagent
--     (see .claude/agents/source-catalog-curator.md). Target ≥200 entries
--     spanning ≥10 categories at Phase-1.5 close.
--   - Each row reuses the existing `source_type` enum (rss, finnhub,
--     reddit_*, x_*, custom_api, etc.) so a catalog row maps 1:1 onto a
--     `sources` row when the user picks it.
--   - `embedding` column (vector(1536)) stores OpenAI text-embedding-3-small
--     output for semantic search by user intent. Generated by the
--     onboarding agent's RAG layer.
--   - paywall_tier covers free / freemium / paid / byos so the agent can
--     filter by user's stated paywall comfort and surface monthly cost
--     transparently.
-- ════════════════════════════════════════════════════════════════════

-- ─── Enums ────────────────────────────────────────────────────────────
-- paywall_tier: 4 buckets the conversational agent uses to filter.
--   free       — anonymous public RSS / API
--   freemium   — free tier exists but paid unlock for full quality
--   paid       — requires subscription. agent surfaces cost.
--   byos       — Bring Your Own Subscription (user pastes existing creds
--                / OAuth, encrypted via external_subscriptions table)
do $$
begin
  if not exists (select 1 from pg_type where typname = 'paywall_tier') then
    create type public.paywall_tier as enum ('free', 'freemium', 'paid', 'byos');
  end if;
end$$;

-- update_cadence: how often the source publishes new content. Drives
-- downstream pipeline expectations (e.g., "weekly" sources don't need
-- 30-min ingest ticks).
do $$
begin
  if not exists (select 1 from pg_type where typname = 'update_cadence') then
    create type public.update_cadence as enum (
      'realtime', 'hourly', 'daily', 'weekly', 'monthly'
    );
  end if;
end$$;

-- ─── Table: source_catalog ────────────────────────────────────────────
create table if not exists public.source_catalog (
  id                          uuid primary key default gen_random_uuid(),

  -- Display
  name                        text not null,
  description                 text not null,         -- one-sentence pitch shown by agent
  url                         text not null,         -- the actual feed/API endpoint

  -- Type (reuses the enum that `sources.type` uses, so picking from
  -- catalog → inserting into `sources` is a direct shape match)
  type                        public.source_type not null,

  -- Taxonomy (RAG layer uses these for matching user intent)
  categories                  text[] not null default '{}',
  subcategories               text[] not null default '{}',
  recommended_for_topics      text[] not null default '{}',

  -- Paywall + cost transparency (agent NEVER auto-adds paid sources;
  -- always confirms cost with the user first — see plan §1.5.4)
  paywall_tier                public.paywall_tier not null default 'free',
  paywall_cost_usd_monthly    numeric(8,2),

  -- Update cadence drives ingest expectations
  update_cadence              public.update_cadence not null default 'daily',

  -- Geography for international/local relevance
  geography                   text[] not null default '{global}',

  -- Quality (curated initially; learned post-Phase-8 from save/dismiss
  -- patterns aggregated through Community Brain)
  quality_score               numeric(4,3) not null default 0.500
    check (quality_score between 0 and 1),

  -- OAuth-required sources (X timelines, private Reddit, YouTube subs)
  -- map onto the existing oauth_provider enum.
  requires_oauth              boolean not null default false,
  oauth_provider              public.oauth_provider,

  -- RAG: semantic search by user intent. Generated server-side from
  -- `name || ' — ' || description || ' Topics: ' || array_to_string(recommended_for_topics, ', ')`
  -- via OpenAI text-embedding-3-small.
  embedding                   vector(1536),

  -- Lifecycle
  is_active                   boolean not null default true,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),

  -- A given (type, url) pair is unique — prevents the curator from
  -- accidentally inserting the same Bloomberg RSS twice.
  constraint source_catalog_type_url_key unique (type, url)
);

comment on table public.source_catalog is
  'Phase-1.5 curated catalog of sources for the AI-assisted onboarding agent. Public read, service_role write. Seeded by source-catalog-curator subagent.';

-- ─── Indexes ──────────────────────────────────────────────────────────
-- Covers the common filter paths the onboarding agent runs:
--   1. By paywall_tier (free-tier users see only 'free'/'freemium')
--   2. By categories (agent narrows by user's stated interest categories)
--   3. By type (when the agent asks "want any podcasts?" specifically)
--   4. Vector ANN over embedding (RAG: top-K matches for user intent)

create index if not exists source_catalog_paywall_idx
  on public.source_catalog (paywall_tier)
  where is_active = true;

create index if not exists source_catalog_type_idx
  on public.source_catalog (type)
  where is_active = true;

create index if not exists source_catalog_categories_gin
  on public.source_catalog using gin (categories);

create index if not exists source_catalog_subcategories_gin
  on public.source_catalog using gin (subcategories);

create index if not exists source_catalog_topics_gin
  on public.source_catalog using gin (recommended_for_topics);

-- IVFFLAT for ANN over the 1536-dim OpenAI embeddings. lists=100 is
-- the standard recommendation for ~10K-50K rows; revisit when catalog
-- grows past that.
create index if not exists source_catalog_embedding_idx
  on public.source_catalog using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

-- ─── Trigger: maintain updated_at ─────────────────────────────────────
-- public.set_updated_at() already exists (initial_schema.sql) and was
-- pinned to search_path=public,pg_temp in 20260504000001_security_advisor_fixes.
create trigger source_catalog_set_updated_at
  before update on public.source_catalog
  for each row execute function public.set_updated_at();

-- ─── RLS ──────────────────────────────────────────────────────────────
-- Catalog is public read (anyone authenticated can browse), service_role
-- write (only the curator subagent / scheduled tasks update).
alter table public.source_catalog enable row level security;

-- READ: any signed-in user
drop policy if exists "source_catalog_read_authenticated" on public.source_catalog;
create policy "source_catalog_read_authenticated"
  on public.source_catalog for select
  to authenticated
  using (is_active = true);

-- READ: also allow anon for the marketing-page "preview the catalog"
-- feature (plan §1.5 followup idea: catalog visible on landing).
-- Restricted to active rows only.
drop policy if exists "source_catalog_read_anon" on public.source_catalog;
create policy "source_catalog_read_anon"
  on public.source_catalog for select
  to anon
  using (is_active = true);

-- WRITE: service_role only. No INSERT/UPDATE/DELETE policy for
-- authenticated/anon means RLS denies by default.

-- ─── Grants ───────────────────────────────────────────────────────────
grant select on public.source_catalog to anon, authenticated;
grant all    on public.source_catalog to service_role;
